# name
name: backend-cd

on:
  # manual
  workflow_dispatch:
  
  # on push
  push:
    branches:
      - main
    paths:
      - "starter/backend/**/*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    # checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # setup Python
    - name: Use Python
      uses: actions/setup-python@v5
      with:
        # use required Python version from Pipfile
        python-version: "3.10"
        # use cache
        cache: "pip"
        cache-dependency-path: starter/backend

    # install dependencies including dev packages for linting
    - name: Install
      working-directory: starter/backend
      run: |
        pip install pipenv
        pipenv install --dev

    # lint
    - name: Lint
      working-directory: starter/backend
      run: |
        pipenv run lint

  test:
    runs-on: ubuntu-latest
    steps:
    # checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # setup Python
    - name: Use Python
      uses: actions/setup-python@v5
      with:
        # use required Python version from Pipfile
        python-version: "3.10"
        # use cache
        cache: "pip"
        cache-dependency-path: starter/backend
    
    # install dependencies
    - name: Install
      working-directory: starter/backend
      run: |
        pip install pipenv
        pipenv install

    # test
    - name: Test
      working-directory: starter/backend
      run: |
        pipenv run test

  build:
    runs-on: ubuntu-latest
    # only if lint and test are successful
    needs: [lint, test]
    steps:
    # checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # log into ECR
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # build Docker image with backend URL variable
    - name: Build and push Docker image
      working-directory: starter/backend
      run: |
        docker build --tag 959819173443.dkr.ecr.us-east-1.amazonaws.com/backend:${GITHUB_SHA} .
        docker push 959819173443.dkr.ecr.us-east-1.amazonaws.com/backend:${GITHUB_SHA}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    # log into ECR
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Deploy Kubernetes manifests
      working-directory: starter/backend/k8s
      run: |
        kustomize edit set image backend=959819173443.dkr.ecr.us-east-1.amazonaws.com/backend:${GITHUB_SHA}
        kustomize build | kubectl apply -f -
